# Generated by Django 4.0.3 on 2022-05-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_items_emailaddress_items_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
