# Generated by Django 4.0.3 on 2022-05-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_items_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='emailAddress',
        ),
        migrations.RemoveField(
            model_name='items',
            name='userName',
        ),
        migrations.AddField(
            model_name='items',
            name='userID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
