# Generated by Django 4.0.3 on 2022-05-05 15:40

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_items_emailaddress_remove_items_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.upload_to, verbose_name='Image')),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
